# solo node
FROM node:latest as node
WORKDIR /app
COPY ./ /app/
RUN npm install
RUN npm run build --prod

# hacer uso de nginx
FROM nginx:latest
COPY --from=node /app/dist/frontend /usr/share/nginx/html
EXPOSE 80