//ESTE ENUM ES UTILIZADO PARA MANEJAR LOS TIPOS DE DATOS QUE SE MANEJAN
//DENTRO DEL LENGUAJE ESPECIFICADO
//-------------------------------------------------
//NOTA: ESTE ENUM SE REFIERE AL MANEJO DE LAS PALABRAS RESERVADAS
const TIPO_DATO = {
    DECIMAL: 'DECIMAL',
    CADENA: 'CADENA',
    BANDERA: 'BANDERA'
}

module.exports = TIPO_DATO