//ESTE ENUM ES UTILIZADO PARA MANEJAR TODOS LOS TIPOS DE INSTRUCCIONES QUE SE MANEJAN
//DENTRO DEL LENGUAJE ESPECIFICADO
const TIPO_INSTRUCCION = {
    COUT: 'INS_COUT',
    DECLARACION: 'DECLARACION'
}

module.exports = TIPO_INSTRUCCION