//ESTE ENUM ES UTILIZADO PARA MANEJAR TODOS LOS TIPOS DE INSTRUCCIONES QUE SE MANEJAN
//DENTRO DEL LENGUAJE ESPECIFICADO
const TIPO_INSTRUCCION = {
    COUT: 'INS_COUT',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO: 'DEC_METODO',
    STARTWITH: 'STARTWITH'
}

module.exports = TIPO_INSTRUCCION