//ESTE ENUM ES UTILIZADO PARA MANEJAR TODOS LOS TIPOS DE OPERACIONES
//DIGASE ARITMETICOS, LOGICOS Y RELACIONALES
const TIPO_OPERACION = {
    SUMA: 'SUMA',
    RESTA: 'RESTA',
    MULTIPLICACION: 'MULTIPLICACION',
    DIVISION: 'DIVISION',
    IGUALIGUAL: 'IGUALIGUAL',
    MENOR: 'MENOR',
    AND: 'AND'
}

module.exports = TIPO_OPERACION