
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int resta = 3;
  public static final int suma = 2;
  public static final int decimal = 7;
  public static final int entero = 6;
  public static final int error = 1;
  public static final int multi = 4;
  public static final int EOF = 0;
  public static final int division = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "suma",
  "resta",
  "multi",
  "division",
  "entero",
  "decimal"
  };
}

